import type { Regulation, Source } from "./types";

const sources: Record<string, Source[]> = {
  ICRC: [{ label: "ICRC — Autonomous weapons and civilian protection", url: "https://www.icrc.org/en/law-and-policy/autonomous-weapons" }],
  UNODA: [{ label: "UNODA — Lethal autonomous weapons systems", url: "https://disarmament.unoda.org/the-convention-on-certain-conventional-weapons/background-on-laws-in-the-ccw/" }],
  OHCHR: [{ label: "OHCHR — Human rights and digital technologies", url: "https://www.ohchr.org/en/privacy-in-the-digital-age" }],
  NIST: [{ label: "NIST — AI Risk Management Framework", url: "https://www.nist.gov/itl/ai-risk-management-framework" }],
  UNEP: [{ label: "UNEP — Climate change and security risks", url: "https://www.unep.org/topics/fresh-water/disasters-and-climate-change/climate-change-and-security-risks" }],
};
const provisional = "Evidence text to be verified: precise standards, performance data, and state practice remain uneven and contested.";
const r = (number: number, id: string, title: string, text: string, evidenceFor: string, evidenceChallenge: string, key = "ICRC"): Regulation => ({ id, number, title, text, evidenceFor, evidenceChallenge, evidenceDataPoint: provisional, sources: sources[key] });

export const defaultRegulations: Regulation[] = [
  r(1,"meaningful-human-control","Meaningful Human Control","Meaningful human control must be maintained over any system capable of using lethal force.","Human judgment can bring legal reasoning, moral responsibility, and sensitivity to changing context into decisions made under extreme pressure.","Machine-speed threats may leave little time for intervention, and states disagree about what level of involvement is genuinely meaningful."),
  r(2,"autonomous-lethal-decisions","Autonomous Lethal Decisions","Decisions to use lethal force must not be made solely by an autonomous system.","A human may be better able to interpret surrender, hesitation, proportionality, and context that cannot be reduced to target data.","Automated systems may apply programmed rules consistently and may be proposed for defensive settings where reaction time is extremely short.","UNODA"),
  r(3,"state-responsibility","State Responsibility","States remain legally and politically responsible for harm caused by AI, drones, autonomous weapons, or robotic systems that they deploy.","Clear state responsibility can reduce accountability gaps and prevent complex supply chains from becoming a shield from scrutiny.","Responsibility may be distributed across commanders, operators, programmers, manufacturers, data providers, and states, making causation difficult."),
  r(4,"civilian-distinction","Civilian Distinction","States must take all feasible precautions to distinguish civilians from combatants when using emerging technologies.","Technical tools may combine sensors and data to improve identification, while the duty to distinguish remains central to civilian protection.","Civilian and combatant roles may be ambiguous, data can be incomplete, and technical classification cannot resolve every contextual judgment."),
  r(5,"wider-civilian-harm","Wider Civilian Harm","Claims of military precision must also consider displacement, fear, infrastructure damage, disruption of daily life, and longer-term political grievances.","A narrow focus on immediate casualties can miss damaged services, trauma, displacement, and grievances that shape longer-term peace.","Indirect and long-term effects are difficult to attribute, predict, and compare during urgent operational decisions."),
  r(6,"independent-technical-evaluation","Independent Technical Evaluation","AI-assisted targeting and security systems must not be deployed when their data, accuracy, biases, and limitations cannot be independently evaluated.","Independent evaluation can reveal unreliable data, hidden bias, and failure modes before they affect life-and-death security decisions.","Governments and companies may resist access to proprietary or classified systems, and evaluators may lack representative operational data.","NIST"),
  r(7,"public-acknowledgment","Public Acknowledgment","States must publicly acknowledge their use of AI-assisted, autonomous, or remotely operated systems in armed operations.","Acknowledgment enables democratic oversight, public debate, and investigation of whether systems are used consistently with law.","Detailed disclosure may expose capabilities, intelligence methods, or vulnerabilities and can conflict with national-security secrecy.","OHCHR"),
  r(8,"independent-investigation","Independent Investigation","Serious allegations of civilian harm involving emerging technologies must be investigated by an independent body.","Independent investigation can strengthen credibility, establish facts, identify failures, and support remedies for affected civilians.","States may regard external investigation as an intrusion on sovereignty, especially where evidence is classified or access is restricted.","OHCHR"),
  r(9,"explanation-and-compensation","Explanation and Compensation","Individuals and communities harmed by unlawful or erroneous operations must have access to explanation, appeal, investigation, and compensation.","Accessible remedies recognize civilian harm, help correct institutional failures, and can rebuild trust between communities and authorities.","Attribution is difficult when systems, data, human operators, and multiple organizations contribute to a harmful outcome.","OHCHR"),
  r(10,"discriminatory-surveillance","Protection from Discriminatory Surveillance","Biometric, facial-recognition, and population-surveillance technologies must not target people solely because of ethnicity, religion, political activity, migration status, or community membership.","Safeguards can reduce collective suspicion, discriminatory profiling, and chilling effects on political and community participation.","Authorities argue surveillance can support legitimate security goals, while bias may be difficult to detect in complex systems.","OHCHR"),
  r(11,"humanitarian-data","Protection of Humanitarian Data","Data collected for humanitarian, medical, migration, or climate-response purposes must not later be repurposed for political repression or unlawful military targeting.","Purpose limits can preserve trust and prevent data gathered to help vulnerable people from later exposing them to repression or attack.","Data sharing can improve emergency response, while future uses and downstream access are hard to control.","OHCHR"),
  r(12,"system-limitations","Disclosure of System Limitations","States and private companies must disclose significant limitations, biases, known error rates, and foreseeable risks in systems used for security decisions.","Disclosure helps decision-makers, oversight bodies, and affected people understand where a system may be unreliable or unsafe.","Companies may invoke intellectual property and states may invoke security, while one error rate can conceal differences between contexts.","NIST"),
  r(13,"essential-resources","Essential Resources","Emerging technologies must not be used to monopolize or coercively control essential climate-sensitive resources, including water, food, energy, or humanitarian aid.","Technology can intensify unequal control over scarce resources during climate stress, increasing vulnerability, coercion, and conflict risk.","Digital systems can also improve allocation, and distinguishing legitimate management from coercive control may be contested.","UNEP"),
  r(14,"affected-communities","Participation of Affected Communities","Climate-vulnerable, conflict-affected, indigenous, minority, and displaced communities must meaningfully participate in decisions about technological systems used in their territories.","Local knowledge can expose overlooked harms, improve legitimacy, and align decisions with the priorities of people most affected.","Meaningful participation takes time, may complicate urgent decisions, and can be difficult where interests compete.","UNEP"),
  r(15,"international-monitoring","International Monitoring","States must support an international monitoring mechanism capable of reviewing high-risk systems and responding to technologies that create unacceptable risks to civilians or international peace.","Shared monitoring could identify cross-border risks and give smaller states access to expertise that is expensive to develop alone.","Oversight may face weak enforcement, sovereignty objections, unequal state influence, and limited access to sensitive systems.","UNODA"),
];
