import type { EvidenceBar, Regulation, Source } from "./types";

const source = (label: string, url: string): Source => ({ label, url });
const bar = (label: string, value: number, max: number, display: string): EvidenceBar => ({ label, value, max, display });

export const defaultRegulations: Regulation[] = [
  {
    id: "human-authorization",
    number: 1,
    title: "Human Authorization for Lethal Force",
    text: "A human commander must identify the intended target, assess distinction and proportionality, and expressly authorize every attack involving lethal force. Fully autonomous target selection is permitted only for point-defence against incoming materiel within a pre-defined area and time window where civilians are not present.",
    evidenceFor: "This rule turns ‘meaningful human control’ into an auditable decision: a named commander, a defined target, a bounded place and time, and a recorded authorization.",
    evidenceChallenge: "Very short reaction times may make individual approval impractical for missile defence, while states may disagree about how narrowly the point-defence exception should be drawn.",
    evidenceDataPoint: "In 2023, 152 states voted for the first UN General Assembly resolution specifically addressing lethal autonomous weapons systems; 4 voted against and 11 abstained.",
    evidenceBars: [bar("For", 152, 167, "152 states"), bar("Abstain", 11, 167, "11"), bar("Against", 4, 167, "4")],
    sources: [source("UN Digital Library — A/RES/78/241 voting record", "https://digitallibrary.un.org/record/4033027")],
  },
  {
    id: "legal-review",
    number: 2,
    title: "Pre-deployment Legal and Technical Review",
    text: "Before procurement or operational use, every high-risk military AI system must undergo an Article 36 legal review and independent technical testing against at least 1,000 documented scenarios, including degraded sensors, surrender, protected sites, and civilian–combatant ambiguity. A public summary and a re-review date no later than 24 months must be published.",
    evidenceFor: "A minimum test set, named scenario classes, publication requirement, and expiry date make review repeatable rather than a one-time internal assurance.",
    evidenceChallenge: "A fixed test count does not guarantee realistic coverage, and states may withhold results because the system, data, or vulnerabilities are classified.",
    evidenceDataPoint: "Although 174 states are party to Additional Protocol I, the ICRC reported that only about 15–20 states were known to conduct their own formal weapons reviews.",
    evidenceBars: [bar("AP I parties", 174, 174, "174 states"), bar("Known reviewers", 20, 174, "about 15–20")],
    sources: [source("ICRC — Legal reviews of new weapons", "https://blogs.icrc.org/law-and-policy/2016/10/06/legal-review-new-weapons/")],
  },
  {
    id: "biometric-targeting",
    number: 3,
    title: "No Biometric-only Targeting",
    text: "No person may be detained, targeted, or denied movement solely on the output of facial recognition, gait recognition, voice identification, or other biometric classification. A trained human must corroborate identity with at least two independent non-biometric sources, and false-positive rates must be published for relevant demographic groups before use.",
    evidenceFor: "Requiring corroboration prevents a probabilistic match from becoming a complete security decision and exposes unequal error rates before deployment.",
    evidenceChallenge: "Independent corroboration can slow time-sensitive operations, and representative performance data may be unavailable in the actual population or operating environment.",
    evidenceDataPoint: "NIST evaluated 189 facial-recognition algorithms from 99 developers and found that, in many one-to-one systems, false-positive rates varied by factors of 10 to more than 100 across demographic groups.",
    evidenceBars: [bar("Lower observed gap", 10, 100, "10×"), bar("Upper observed gap", 100, 100, ">100×")],
    sources: [source("NIST — Demographic effects in face recognition", "https://www.nist.gov/news-events/news/2019/12/nist-study-evaluates-effects-race-age-sex-face-recognition-software")],
  },
  {
    id: "incident-accountability",
    number: 4,
    title: "Incident Logs, Investigation, and Remedy",
    text: "High-risk systems must preserve tamper-evident decision logs for 10 years. Alleged civilian-harm incidents must receive an initial public notice within 30 days and an independent investigation within 90 days. Affected people must have access to a human appeal and, where harm is unlawful, compensation.",
    evidenceFor: "Deadlines and retained logs give investigators a usable record before evidence disappears and provide affected communities with a predictable path to remedy.",
    evidenceChallenge: "Operational secrecy, disputed causation, and active conflict may prevent complete publication or investigation within the proposed timetable.",
    evidenceDataPoint: "The proposed accountability clock is 30 days for initial notice, 90 days for investigation, and 10 years for preservation of decision records.",
    evidenceBars: [bar("Initial notice", 30, 90, "30 days"), bar("Investigation", 90, 90, "90 days")],
    sources: [source("OHCHR — Right to privacy in the digital age", "https://www.ohchr.org/en/privacy-in-the-digital-age")],
  },
  {
    id: "humanitarian-data-firewall",
    number: 5,
    title: "Humanitarian Data Firewall",
    text: "Data collected to provide humanitarian, medical, migration, or disaster assistance must not be used for targeting, detention, immigration enforcement, or political surveillance. Access must be logged, sensitive data encrypted, breaches reported to affected organizations within 72 hours, and identifiable records deleted when the assistance purpose ends.",
    evidenceFor: "Purpose limitation and short breach notification protect people who cannot realistically refuse data collection when seeking essential assistance.",
    evidenceChallenge: "Emergency coordination may require rapid data sharing, while deletion schedules and downstream access are difficult to enforce across many partners.",
    evidenceDataPoint: "A 2022 cyberattack on an ICRC data host compromised personal data concerning more than 515,000 highly vulnerable people.",
    evidenceBars: [bar("People affected", 515000, 600000, ">515,000")],
    sources: [source("ICRC — Cyberattack: what we know", "https://www.icrc.org/en/document/cyber-attack-icrc-what-we-know")],
  },
  {
    id: "displaced-persons",
    number: 6,
    title: "Non-digital Access for Displaced People",
    text: "Registration for asylum, food, shelter, health care, and cash assistance must provide a non-biometric alternative. Refusal or inability to supply fingerprints, iris scans, or a smartphone credential must not by itself reduce eligibility, and every automated denial must receive human review within 7 days.",
    evidenceFor: "An alternative route prevents identity technology from becoming a new barrier to survival for people with damaged documents, disabilities, or security concerns.",
    evidenceChallenge: "Parallel processes cost more and may make duplicate-registration or fraud controls harder for agencies operating with limited staff.",
    evidenceDataPoint: "UNHCR estimated that 117.3 million people were forcibly displaced worldwide at the end of 2023.",
    evidenceBars: [bar("Forcibly displaced", 117.3, 130, "117.3 million")],
    sources: [source("UNHCR — Global Trends 2023", "https://www.unhcr.org/publications/global-trends-2023")],
  },
  {
    id: "essential-resources",
    number: 7,
    title: "Human Review of Essential-resource Decisions",
    text: "No automated system may unilaterally terminate a household’s access to drinking water, staple-food assistance, or essential household energy. Adverse decisions must state the data used, offer a free offline appeal, and receive human review within 7 days; service must continue during an appeal where life or health is at risk.",
    evidenceFor: "A continuity rule and rapid offline appeal keep data errors or connectivity gaps from immediately becoming threats to health and security.",
    evidenceChallenge: "Continuing service during appeals may strain scarce supplies and budgets, particularly during drought, displacement, or infrastructure collapse.",
    evidenceDataPoint: "WHO and UNICEF estimated that 2.2 billion people lacked safely managed drinking-water services in 2022.",
    evidenceBars: [bar("Without safely managed water", 2.2, 8, "2.2 billion"), bar("World population", 8, 8, "about 8 billion")],
    sources: [source("WHO/UNICEF — WASH monitoring", "https://www.who.int/teams/environment-climate-change-and-health/water-sanitation-and-health/monitoring-and-evidence/wash-monitoring")],
  },
  {
    id: "chemical-weapons-ai",
    number: 8,
    title: "AI and Chemical-weapons Prohibition",
    text: "States must prohibit AI systems from designing, optimizing, acquiring, or selecting targets for chemical weapons. Relevant dual-use facilities must declare covered AI-assisted activities to the national authority, retain auditable records for 10 years, and permit inspection under Chemical Weapons Convention procedures.",
    evidenceFor: "Connecting AI-enabled activity to an established treaty system supplies declarations, national authorities, inspections, and a near-universal legal baseline.",
    evidenceChallenge: "Legitimate chemistry and pharmaceutical research uses similar tools, so verification must distinguish prohibited weapon activity from peaceful dual-use work.",
    evidenceDataPoint: "The OPCW has 193 member states; by 2019 it had conducted more than 3,900 Article VI inspections at declared industrial facilities. More than 97% of declared chemical-weapon stockpiles have since been destroyed.",
    evidenceBars: [bar("OPCW membership", 193, 195, "193 states"), bar("Declared stockpiles destroyed", 97, 100, ">97%")],
    sources: [source("OPCW — Article VI declarations and inspections", "https://www.opcw.org/media-centre/news/2019/09/national-stakeholders-gain-advanced-knowledge-article-vi-declaration-0")],
  },
  {
    id: "public-register",
    number: 9,
    title: "Public Register and Independent Audit",
    text: "Each state must maintain an annual public register of high-risk security AI systems listing the responsible authority, purpose, legal basis, deployment dates, evaluation method, known error ranges, civilian-harm incidents, and audit date. An independent body must audit each deployed system at least once every 24 months.",
    evidenceFor: "Standard fields and an audit cycle allow legislatures, researchers, and affected communities to compare official claims with operational outcomes.",
    evidenceChallenge: "Detailed disclosure can reveal capabilities or vulnerabilities, while smaller states may lack qualified independent auditors.",
    evidenceDataPoint: "NIST’s large facial-recognition study covered 189 algorithms from 99 developers, illustrating that independent comparative evaluation can operate across many proprietary systems.",
    evidenceBars: [bar("Algorithms tested", 189, 200, "189"), bar("Developers", 99, 200, "99")],
    sources: [source("NIST — Face Recognition Vendor Test", "https://www.nist.gov/news-events/news/2019/12/nist-study-evaluates-effects-race-age-sex-face-recognition-software")],
  },
  {
    id: "international-monitoring",
    number: 10,
    title: "International Notification and Emergency Pause",
    text: "States must notify a designated international monitoring mechanism at least 60 days before deploying a new high-risk autonomous weapon category and within 72 hours of any serious civilian-harm incident. The mechanism may request records, convene a technical inquiry, and recommend a temporary deployment pause pending investigation.",
    evidenceFor: "Advance notice, rapid incident reporting, and a temporary pause create concrete opportunities for prevention without requiring an immediate universal enforcement authority.",
    evidenceChallenge: "States may reject external review on sovereignty or security grounds, and a recommendation may be ignored without agreed consequences.",
    evidenceDataPoint: "The 2023 UN vote on autonomous weapons produced 152 votes in favour, but 15 states voted against or abstained—broad support without full consensus.",
    evidenceBars: [bar("For UN action", 152, 167, "152 states"), bar("Against or abstaining", 15, 167, "15")],
    sources: [source("UN Digital Library — A/RES/78/241", "https://digitallibrary.un.org/record/4033027")],
  },
];
